### ISSUE TITLE
error during importing tensorflow 

### ISSUE THREAD

**Issue by raistefintel** [intel/intel-extension-for-tensorflow#13]
NotFoundError: libmkl_sycl.so.2: cannot open shared object file: No such file or directory
After some research I thought that adding the location of libmkl_sycl.so.2 to the system library path would solve it, but it didn't do so. any suggestions?

**Comment by raistefintel** [comment]
> NotFoundError: libmkl_sycl.so.2: cannot open shared object file: No such file or directory After some research I thought that adding the location of libmkl_sycl.so.2 to the system library path would solve it, but it didn't do so. any suggestions?

I am trying to use ITEX with GPU flex series by the way, so I already went through the installation of oneAPI libraries and the drivers

**Comment by yiqianglee** [comment]
@raistefintel a little strange, we have done many mkl UT in our side, have you run `source /opt/intel/oneapi/setvars.sh` before execution? 

And also, can you please paste the output of `ldd` libitex_gpu.so, like `ldd ~/miniconda3/envs/yli135/lib/python3.9/site-packages/tensorflow-plugins/libitex_gpu.so`? @GHGmc2

**Comment by GHGmc2** [comment]
@raistefintel please ensure oneMKL from basekit is installed, and set runtime env vars as per: https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_gpu.md#install-via-pypi-wheel-in-bare-metal
```bash
# 4 components are necessary: DPC++/C++ Compiler, DPC++ Libiary, Threading Building Blocks and oneMKL
$ sudo sh ./l_BaseKit_p_2022.3.0.8767_offline.sh

source /opt/intel/oneapi/setvars.sh
```

You can also find the solution on FAQ: https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/guide/FAQ.md#runtime

**Comment by raistefintel** [comment]
My bad, I forgot to set the runtime env variables, no issue afterwards, thank you
