### ISSUE TITLE
hi, I am getting below error while running tensorflow in spyder. tensorflow version is 2.7 and python is 3.9. My machine is windows 11 with IRIS Xe graphics. 

### ISSUE THREAD

**Issue by Pranjali87** [intel/intel-extension-for-tensorflow#15]

**Comment by yiqianglee** [comment]
@Pranjali87 I'm not clear about your question, the minimal TF version for ITEX is 2.10, can you try again after upgrading TF to 2.10?

**Comment by yinghu5** [comment]
Seems not Intel extension for tensorflow issues. close.  for windows installation, please try WSL. thanks

For Windows 10 or Windows 11

[Windows Subystem for Linux 2](https://learn.microsoft.com/en-us/windows/wsl/about) (WSL2) with Ubuntu 22.04 (64-bit)
