### ISSUE TITLE
check if GPU is detected by tensorflow

### ISSUE THREAD

**Issue by raistefintel** [intel/intel-extension-for-tensorflow#16]
Right now tf.config.list_physical_devices('GPU') gives 0, will this be fixed in the future? how can one check that TF (ITEX installed) is running on GPU?

**Comment by raistefintel** [comment]
> @raistefintel the device type we registered to TensorFlow is "XPU", you can use `tf.config.list_physical_devices('XPU')` to check if ITEX is installed.

And if XPU is 1 how do we know it's using the GPU and not the CPU?

**Comment by yiqianglee** [comment]
@raistefintel , currently, ITEX XPU only supports GPU backend. 
In future, we will add "CPU backend" support which can be configured by `set_backend`, you can see below for details [link](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/guide/python_api.md#set-intel-extension-for-tensorflow-backend)

**Comment by raistefintel** [comment]
> @raistefintel , currently, ITEX XPU only supports GPU backend. In future, we will add "CPU backend" support which can be configured by `set_backend`, you can see below for details [link](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/guide/python_api.md#set-intel-extension-for-tensorflow-backend), but "CPU backend" feature is not ready yet.

Ok, thanks for the clarification
