### ISSUE TITLE
Intel extension for tensorflow not available on dockerhub

### ISSUE THREAD

**Issue by rahulunair** [intel/intel-extension-for-tensorflow#2]
Hey All, 

Congragulations on the release of the first version of the intel extension for Tensorflow, I tried to pull the docker image from dockerhub using:

```bash
docker pull intel/intel-extension-for-tensorflow:gpu
```

But I am getting an error message:

```bash
┌rahul@arcle ~
└> docker pull intel/intel-extension-for-tensorflow:gpu                                                           
Error response from daemon: pull access denied for intel/intel-extension-for-tensorflow, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
The image is not available on dockerhub as well: https://hub.docker.com/r/intel/intel-extension-for-tensorflow/. Could you please check if the image visibility is set to `private`.

**Comment by yiqianglee** [comment]
Really thanks for your quick try @rahulunair . 
The dock is under the final process to push out for public available, it will be finished in couple of days, we will update issue when it's available. @Dboyqiao

**Comment by unrahul** [comment]
Thank you @yiqianglee and @Dboyqiao !

**Comment by Dboyqiao** [comment]
@rahulunair The docker image is available on dockerhub: https://hub.docker.com/r/intel/intel-extension-for-tensorflow/, please enjoy!

**Comment by unrahul** [comment]
hi @Dboyqiao apologize for the delay

I just tried the docker image and am able to list xpus on my platform, thank you!:

```bash
vice_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: xxxx
xla_global_id: -1
, name: "/device:XPU:0"
device_type: "XPU"
locality {
  bus_id: 1
}
incarnation: xxxx
physical_device_desc: "device: 0, name: XPU, pci bus id: <undefined>"
xla_global_id: -1
, name: "/device:XPU:1"
device_type: "XPU"
locality {
  bus_id: 1
}
incarnation: xxx
physical_device_desc: "device: 1, name: XPU, pci bus id: <undefined>"
xla_global_id: -1
]
```
Kindly close the ticket..

**Comment by yiqianglee** [comment]
Issue is solved.
