### ISSUE TITLE
Missing files: libcudart, libnvinfer, libcuda, TensorRT libraries

### ISSUE THREAD

**Issue by drelliotlee** [intel/intel-extension-for-tensorflow#22]
I have a new laptop intel i7-12700h CPU + intel arc 370M GPU. I have been following [the instructions here](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_gpu.md#install-gpu-drivers) on a completely fresh install of Ubuntu 22.04. I am able to complete all previous steps and installs, [including those for graphics drivers here](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-dc.html), with zero errors. 

But when I get to the final step to verify the installation `python -c "import intel_extension_for_tensorflow as itex; print(itex.__version__)"` I get this output:

```
2023-02-12 01:10:54.428961: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-12 01:10:54.500062: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-12 01:10:54.501991: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-12 01:10:54.502002: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-12 01:10:54.860563: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-12 01:10:54.860596: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-12 01:10:54.860599: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-12 01:10:55.342112: I itex/core/devices/gpu/itex_gpu_runtime.cc:129] Selected platform: Intel(R) Level-Zero
2023-02-12 01:10:55.342141: I itex/core/devices/gpu/itex_gpu_runtime.cc:154] number of sub-devices is zero, expose root device.
2023-02-12 01:10:55.342144: I itex/core/devices/gpu/itex_gpu_runtime.cc:154] number of sub-devices is zero, expose root device.
2023-02-12 01:10:55.342250: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-12 01:10:55.342257: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-12 01:10:55.342267: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lnvo): /proc/driver/nvidia/version does not exist
1.1.0
Floating point exception (core dumped)
```

So it looks like I am missing these files:
* TensorRT libraries 
* libcudart.so.11.0
* libnvinfer.so.7
* libcuda.so.1

Any ideas what I might be doing wrong?

**Comment by yinghu5** [comment]
Hi, 
As Intel extension for Tensorflow is a plugin of Tensorflow for Intel XPU.  These missing Files (TensorRT libraries etc) are warnings, don't affect the run time env. The key problem looks be Floating point exception (core dumped). 

could you please try   
>source /opt/intel/oneapi/setvars.sh
>sycl-ls

and see if you can see the two GPU ( intel i7-12700h CPU, which shoudl have iGPU also) + intel arc 370M GPU   and Floating point exception (core dumped) again?

Then please try 

export NEOReadDebugKeys=1
 export UseVmBind=0
sycl-ls

If the core dump is gone, then the please use the two environments (which help a known driver issues) in your environment always, then try 

python -c "import intel_extension_for_tensorflow as itex; print(itex.__version__)"

if the problem still insists, then we may need recheck the driver, for example, show the clinfo information as:
https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-dc.html.

**Comment by drelliotlee** [comment]
Thank you for your reply

> source /opt/intel/oneapi/setvars.sh
> sycl-ls

outputs:

```
[opencl:acc:0] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.14.7.0.30_160000]
[opencl:cpu:1] Intel(R) OpenCL, 12th Gen Intel(R) Core(TM) i7-12700H 3.0 [2022.14.7.0.30_160000]
[opencl:acc:2] Intel(R) FPGA Emulation Platform for OpenCL(TM), Intel(R) FPGA Emulation Device 1.2 [2022.15.12.0.01_081451]
[opencl:gpu:3] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x5693] 3.0 [22.43.24595.35]
[opencl:gpu:4] Intel(R) OpenCL HD Graphics, Intel(R) Graphics [0x46a6] 3.0 [22.43.24595.35]
[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) Graphics [0x5693] 1.3 [1.3.24595]
[ext_oneapi_level_zero:gpu:1] Intel(R) Level-Zero, Intel(R) Graphics [0x46a6] 1.3 [1.3.24595]
[host:host:0] SYCL host platform, SYCL host device 1.2 [1.2]
```

so it seems like my computer recognizes both GPUs. But I also did a small sanity check. I ran benchmark program glmark2 both before and after the graphics driver installation, and the score doubled, which convinced me that driver installation worked. 

With your instructions, I no longer get the floating point exception, but now get this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/elliot/.local/lib/python3.9/site-packages/intel_extension_for_tensorflow/__init__.py", line 17, in <module>
    import tensorflow  # pylint: disable=unused-import
  File "/home/elliot/.local/lib/python3.9/site-packages/tensorflow/__init__.py", line 440, in <module>
    _ll.load_library(_plugin_dir)
  File "/home/elliot/.local/lib/python3.9/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core
```

Also, I not sure if this is relevant, but I erroneously said that I was able to follow all steps with no errors. I forgot that I did get one error. `lspci -v |grep -A8 VGA` produces the following output:

```
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 380b
	Flags: bus master, fast devsel, latency 0, IRQ 186, IOMMU group 1
	Memory at 6101000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 4000000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
```

So it seems like my motherboard/bios is incapable of Resizable BAR. could this be causing the errors?

If this is the source of the problem, I find it fascinating that Lenovo would put a Intel Arc GPU on a motherboard/bios which is incapable of using that GPU.

**Comment by drelliotlee** [comment]
Closing this issue because I believe the cause may be that lenovo amazingly just put an intel arc GPU on a motherboard which cannot properly utilize it / is not creating BIOS drivers which can use it (perhaps on windows but maybe not on linux).

**Comment by yinghu5** [comment]
Hi 
Thank you for detail information. 
About the error : tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core.   let's check first from tensorflow environment, then the driver parts. 

Could you please tell how do you create and activate the test environment where intel tensorflow install?

Please try 
>source /path to basekit/intel/oneapi/compiler/latest/env/vars.sh
>source /path to basekit/intel/oneapi/mkl/env/latest/vars.sh
and see if the symbol can be resolved.

OR 

Recommend the guide as the doc
https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_gpu.md

I usually have miniconda installed firstly, then create an conda environment based on that
conda create -n  intel_tf111 python=3.9
conda activate intel_tf111
**python -m pip** install tensorflow==2.11   -->  here use python -m pip,  instead of pip (system provide)
**python -m pip** pip install --upgrade intel-extension-for-tensorflow[gpu]

when start the environment, instead of  source /opt/intel/oneapi/setup.vars 

Please source that library by the below command 
source /path to basekit/intel/oneapi/compiler/latest/env/vars.sh
source /path to basekit/intel/oneapi/mkl/env/latest/vars.sh

then run test code.

**Comment by drelliotlee** [comment]
I have been trying with the python environment which comes pre-installed with ubuntu, but i just tried it with miniconda and the instructions you gave:

```
(download miniconda)
bash /home/elliot/Downloads/Miniconda3-py310_23.1.0-1-Linux-x86_64.sh
(follow instructions)
(start a new terminal now which is in conda's base environment)
conda create -n intel_tf111 python=3.10
conda activate intel_tf111
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/mkl/latest/env/vars.sh
python -m pip install tensorflow==2.11 
python -m pip install --upgrade intel-extension-for-tensorflow[gpu]
python -c "import intel_extension_for_tensorflow as itex; print(itex.__version__)"
```

However I still get the same `undefined symbol: mkl_serv_register_sycl_with_core` error.

Every other test indicates that my computer does detect and does use the arc 370m gpu, so it's a bit of a mystery. 

Thank you for your help Yinghu5, but unfortunately I have lost too much time trying to make this work and will exchange this computer for one with a nvidia gpu. Feel free to close this issue, or leave it open in case others in the future have the same issue.

**Comment by yinghu5** [comment]
Hi  

Sorry for hearing that. We can't reproduce your problem. but  I thought you almost reach the finish. 
  
As you see,  the error like  undefined symbol: mkl_serv_register_sycl_with_core error. is often caused by  the missing libraries. 

The symbol were defined in the /opt/intel/oneapi/lib/intel64/libmkl_core.so

(intel_tf111) intel@intel-L16W:~/intel/oneapi/mkl/latest/lib/intel64$ nm -D libmkl_sycl.so.3 | grep mkl_serv_register_*
                 U mkl_serv_register_sycl_with_core
(intel_tf111) intel@intel-L16W:~/intel/oneapi/mkl/latest/lib/intel64$ nm -D libmkl_core.so | grep mkl_serv_register_*
000000000022d680 T mkl_serv_register_jit_function
000000000022ae80 T mkl_serv_register_sycl_with_core
(intel_tf111) intel@intel-L16W:~/intel/oneapi/mkl/latest/lib/intel64$ ls

In general, the libraries should already LD_LIBRARY_PATH by source /opt/intel/oneapi/mkl/latest/env/vars.sh.  If you have it in your folder,  

We provides one script to check your environment.   https://github.com/intel/intel-extension-for-tensorflow/blob/main/tools/env_check.sh

If possible, please reinstall your oneAPI based toolkits and run it,  maybe help more other developers.

Thanks
Ying


![image](https://user-images.githubusercontent.com/43240216/218944675-4ca14043-c82e-4bb7-8f97-fe05f71f007d.png)

**Comment by NeoZhangJianyu** [comment]
@drelliotlee
Could run the cmd and share the output?
```
icpx --version
```

**Comment by drelliotlee** [comment]
I apologize that I can't help any longer because I already reset and returned the PC, but if it helps:

1.  [here is all the exact hardware on that laptop](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/ideapad-s-series-netbooks/slim-7-16iah7/82vb/82vb0000us/yx047jnh?linkTrack=Homepage%3ABody_Search%20Products&searchType=6&keyWordSearch=YX047JNH)

2. This was on Ubuntu 22.04.1 LTS

3. Also, if it is relevant, I installed oneApi via the GUI installer. 

```
wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19079/l_BaseKit_p_2023.0.0.25537_offline.sh
sudo sh ./l_BaseKit_p_2023.0.0.25537_offline.sh
```

and not via the terminal (`sudo apt-get install intel-oneapi-runtime-dpcpp-cpp intel-oneapi-runtime-mkl`)

Other than that, I feel following the github instructions was fairly straightforward and nothing notable.

**Comment by NeoZhangJianyu** [comment]
OK!
I got the answer from your feedback: oneAPI is 2023.0.0. 
We continue checking this issue in local PC and update the guide.

Thank your feedback!

**Comment by drelliotlee** [comment]
What is the difference between plain old vanilla `python` (from pip) and `intelpython3_full` (in intel's conda channel) ? I wonder if it would have worked with the latter?

I was also confused by the difference between:
1. `intel-aikit-data-ml-tensorflow`
2. `intel-tensorflow`, and 
3. `tensorflow` + ` intel-extension-for-pytorch`

They are all actively being maintained and updated, so there must be some significant difference, but I cannot find any documentation on how they are different. @NeoZhangJianyu @yinghu5

**Comment by NeoZhangJianyu** [comment]
@drelliotlee 
I explain them:
`intel-aikit-tensorflow` and `intel-tensorflow` are same software with different distributed channel.
Bot them are optimized for Intel CPU.

`intel-extension-for-tensorflow` are a plugin of `tensorflow` for Intel GPU and CPU.
But it need to cooperate with tensorflow.

For Intel CPU user:
  `intel-tensorflow` is recommended.
  `stock tensorflow` (Google release) is using oneDNN code path as default from 2.9, which is optimized for Intel CPU too.
  `intel-extension-for-tensorflow for CPU` has same optimize method of `intel-tensorflow` and `stock tensorflow`. It will include more new Intel technology to optimize based on Intel CPU hardware and software feature in the future.
  for example,  `intel-extension-for-tensorflow for CPU` provide [Advanced Auto Mixed Precision](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/guide/advanced_auto_mixed_precision.md) feature to support BF16 with better performance on Intel 4th Xeon (SPR).
 
For Intel GPU user:
  `intel-extension-for-tensorflow` + tensorflow is only method by now.

For both Intel CPU & GPU user:
  `intel-extension-for-tensorflow` will support Intel CPU & GPU in same time in the future. It's the final solution to support tensorflow in Intel CPU & GPU.

**Comment by NeoZhangJianyu** [comment]
@drelliotlee 
Is your case for company or private project?

We are improving `intel-extension-for-tensorflow` user experience in usage now.
We welcome you try it in the future and feedback your experience for any issue. :)

**Comment by Oscilloscope98** [comment]
> `intel-extension-for-tensorflow for CPU` has same optimize method of `intel-tensorflow` and `stock tensorflow`. It will include more new Intel technology to optimize based on Intel CPU hardware and software feature in the future. 

Hi @NeoZhangJianyu !

Could you explain a little bit more about the relationship between `intel-extension-for-tensorflow` and `intel-tensorflow`? Do you mean that `tensorflow` + `itex` could cover the optimizations of `intel-tensorflow` on Intel CPU with some more acceleration features?

Is it recommended to install `intel-tensorflow` together with `itex` on Intel CPU? If so, how could we do this? As currently `itex 1.1.0` requires `tensorflow>=2.10.0`, it seems that if I want to install `itex` with `intel-tensorflow`, I will have both `intel-tensorflow` and `tensorflow` in my environment, which seems to be not so expected.

Thanks in advance!

**Comment by NeoZhangJianyu** [comment]
@Oscilloscope98 
`intel-tensorflow` is a clone of `stock tensorflow`.  `intel-tensorflow` follows `stock tensorflow` version and base code/feature.
It's independent product and distributed. It's added to Intel optimization for Tensorflow.

`intel-extension-for-tensorflow` is a plugin which must cooperate with `stock tensorflow` or `intel-tensorflow`.
`tensorflow` + `itex` can cover the **most** of optimization of `intel-tensorflow` on Intel CPU, because some features can't be implemented in a plugin. That's why `intel-tensorflow` will be present after `itex` is released. 

In the future, most new features will be implemented in `itex`.

`itex` can work well with `tensorflow` or `intel-tensorflow`. In the guide, `tensorflow>=2.10.0` is for both `stock tensorflow` and `intel-tensorflow`, because `intel-tensorflow` follows `stock tensorflow`'s version, code and base feature.

So, before install `itex`, only need to install one of `intel tensorflow` or `stock tensorflow`.

**Comment by Oscilloscope98** [comment]
Hi @NeoZhangJianyu !

Thank you for the detailed explanation!

I tried to install `itex` after installing `intel-tensorflow` (without `stock tensorflow`) as follows:

```bash
[~]# pip list | grep tensorflow
intel_tensorflow             2.10.0
tensorflow-estimator         2.10.0
tensorflow-io-gcs-filesystem 0.30.0

[~]# pip install --upgrade intel-extension-for-tensorflow[cpu]
Collecting intel-extension-for-tensorflow[cpu]
  Using cached intel_extension_for_tensorflow-1.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)
Requirement already satisfied: wheel in /root/miniconda3/envs/test/lib/python3.8/site-packages (from intel-extension-for-tensorflow[cpu]) (0.37.1)
Requirement already satisfied: grpcio>=1.8.6 in /root/miniconda3/envs/test/lib/python3.8/site-packages (from intel-extension-for-tensorflow[cpu]) (1.51.1)
Collecting numpy<1.24
  Using cached numpy-1.23.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting tensorflow>=2.10
  Downloading tensorflow-2.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (588.3 MB)
     ━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/588.3 MB 11.0 MB/s eta 0:00:42
```

However, it seems that `itex` requires `tensorflow >= 2.10` in its [`setup requirements`](https://github.com/intel/intel-extension-for-tensorflow/blob/65d933f0ede0f9c3ee577e03dfe1739ce5811f0f/itex/tools/pip_package/itex_setup.py#L58), and will still automatically install `tensorflow >= 2.10` even though `intel-tensorflow==2.10.0` is already installed.

Could you let me know how to resolve this problem? Thank you!

**Comment by NeoZhangJianyu** [comment]
@Oscilloscope98 
Could you create new issue in this repo for your question?
We hope the issue/answer match the title to help more user.

Thank you!

**Comment by Oscilloscope98** [comment]
> Could you create new issue in this repo for your question? We hope the issue/answer match the title to help more user.

@NeoZhangJianyu Sure! Has raised the issue.

**Comment by yinghu5** [comment]
@drelliotlee and who have gotten the error:    tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core

we found a new case for your reference:  #26 ,   mixing the earlier oneAPI/mkl 2022.2 version will produce the same errors. 
Resolution:  checked the LD_LIBRARY_PATH, align with the required version with installation guide. (mkl 2023.0 currently)
