### ISSUE TITLE
will AVX512 instruction have support for windows?

### ISSUE THREAD

**Issue by leo-smi** [intel/intel-extension-for-tensorflow#25]
I have intel iris Xe and there's support
![image](https://user-images.githubusercontent.com/20663547/222620452-c2324b59-8989-4bdd-9644-b7f9d718e4e0.png)

**Comment by guizili0** [comment]
Hi @leo-smi  do you want to run Intel CPU on GPU, the AVX512 you showed here is for CPU but the iris Xe is the GPU.

For Windows support, both CPU and GPU is under WSL, same with official TensorFlow.
You can find detail in: https://www.tensorflow.org/install/pip#windows-native and https://www.tensorflow.org/install/pip#windows-wsl2

**Comment by leo-smi** [comment]
Thank you
