### ISSUE TITLE
libsycl.so?

### ISSUE THREAD

**Issue by dyedd** [intel/intel-extension-for-tensorflow#26]
when I used the following command:`python -c "import intel_extension_for_tensorflow as itex; print(itex.__version__)"`
then:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xx/.conda/envs/tf/lib/python3.9/site-packages/intel_extension_for_tensorflow/__init__.py", line 17, in <module>
    import tensorflow  # pylint: disable=unused-import
  File "/home/xx/.conda/envs/tf/lib/python3.9/site-packages/tensorflow/__init__.py", line 439, in <module>
    _ll.load_library(_plugin_dir)
  File "/home/xx/.conda/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: libsycl.so.6: cannot open shared object file: No such file or directory

GPU:Arc 770
WSL2

**Comment by guizili0** [comment]
libsycl.so is from intel oneapi.
Please help to follow this doc https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/experimental/install_for_arc_gpu.md to install the required software for intel Arc GPU.

**Comment by dyedd** [comment]
> libsycl.so is from intel oneapi. Please help to follow this doc https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/experimental/install_for_arc_gpu.md to install the required software for intel Arc GPU.

Hello, I have tried this tutorial. I already have this environment.

**Comment by guizili0** [comment]
> > libsycl.so is from intel oneapi. Please help to follow this doc https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/experimental/install_for_arc_gpu.md to install the required software for intel Arc GPU.
> 
> Hello, I have tried this tutorial. I already have this environment.

Did you source /opt/intel/oneapi/setvars.sh?
Can you help to share your env result?

**Comment by dyedd** [comment]
> source /opt/intel/oneapi/setvars.sh

yes，
:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.1.16(1)-release
   args: Using "$@" for setvars.sh arguments:
:: advisor -- latest
:: ccl -- latest
:: clck -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: inspector -- latest
:: ipp -- latest
:: ippcp -- latest
:: itac -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vpl -- latest
:: vtune -- latest
:: oneAPI environment initialized ::

**Comment by dyedd** [comment]
now，it has a new problem：`tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core`

**Comment by guizili0** [comment]
> now，it has a new problem：`tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core`

Thanks, please help to share the itex version and mkl version your are using.
itex version use:
`pip list | grep tensorflow`
mkl version can use: 
`ll /opt/intel/oneapi/mkl/latest -l`

**Comment by dyedd** [comment]
> pip list | grep tensorflow
`pip list | grep tensorflow`:

> intel-extension-for-tensorflow     1.1.0
intel-extension-for-tensorflow-lib 1.1.0.1
tensorflow                         2.10.0
tensorflow-estimator               2.10.0
tensorflow-io-gcs-filesystem       0.31.0

`ll /opt/intel/oneapi/mkl/latest -l`

> lrwxrwxrwx 1 root root 8 Dec  4 22:04 /opt/intel/oneapi/mkl/latest -> 2022.2.1/

**Comment by guizili0** [comment]
> > pip list | grep tensorflow
> > `pip list | grep tensorflow`:
> 
> > intel-extension-for-tensorflow     1.1.0
> > intel-extension-for-tensorflow-lib 1.1.0.1
> > tensorflow                         2.10.0
> > tensorflow-estimator               2.10.0
> > tensorflow-io-gcs-filesystem       0.31.0
> 
> `ll /opt/intel/oneapi/mkl/latest -l`
> 
> > lrwxrwxrwx 1 root root 8 Dec  4 22:04 /opt/intel/oneapi/mkl/latest -> 2022.2.1/

Thanks, this issue is version miss match, please upgrade your oneAPI to 2023.0.

**Comment by dyedd** [comment]
> ll /opt/intel/oneapi/mkl/latest -l

I updated the version, but it is still undefined symbol: mkl_serv_register_sycl_with_core

**Comment by guizili0** [comment]
> > ll /opt/intel/oneapi/mkl/latest -l
> 
> I updated the version, but it is still undefined symbol: mkl_serv_register_sycl_with_core
> 
> bove are installed properly. Traceback (most recent call last): File "", line 1, in File "/home/xxxx/.conda/envs/tf/lib/python3.9/site-packages/intel_extension_for_tensorflow/**init**.py", line 17, in import tensorflow # pylint: disable=unused-import File "/home/xxxx/.conda/envs/tf/lib/python3.9/site-packages/tensorflow/**init**.py", line 439, in _ll.load_library(_plugin_dir) File "/home/xxxx/.conda/envs/tf/lib/python3.9/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library py_tf.TF_LoadLibrary(lib) tensorflow.python.framework.errors_impl.NotFoundError: /opt/intel/oneapi/lib/intel64/libmkl_sycl.so.3: undefined symbol: mkl_serv_register_sycl_with_core

can you help to share the result?
`env | grep LD_LIBRARY_PATH`

**Comment by dyedd** [comment]
> env | grep LD_LIBRARY_PATH

```
LD_LIBRARY_PATH=/opt/intel/oneapi/vpl/2022.2.5/lib:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.1//lib/release:/opt/intel/oneapi/mpi/2021.7.1//lib:/opt/intel/oneapi/mkl/2022.2.1/lib/intel64:/opt/intel/oneapi/itac/2021.7.1/slib:/opt/intel/oneapi/ippcp/2021.6.2/lib/intel64:/opt/intel/oneapi/ipp/2021.6.2/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/dep/lib:/opt/intel/oneapi/dal/2021.7.1/lib/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.7.1/lib/cpu_gpu_dpcpp
```
It's very strange. Just now I have followed oneapi2023？？？

**Comment by guizili0** [comment]
> > env | grep LD_LIBRARY_PATH
> 
> ```
> LD_LIBRARY_PATH=/opt/intel/oneapi/vpl/2022.2.5/lib:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.1//lib/release:/opt/intel/oneapi/mpi/2021.7.1//lib:/opt/intel/oneapi/mkl/2022.2.1/lib/intel64:/opt/intel/oneapi/itac/2021.7.1/slib:/opt/intel/oneapi/ippcp/2021.6.2/lib/intel64:/opt/intel/oneapi/ipp/2021.6.2/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/dep/lib:/opt/intel/oneapi/dal/2021.7.1/lib/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.7.1/lib/cpu_gpu_dpcpp
> ```
> 
> It's very strange. Just now I have followed oneapi2023？？？

1. Please help to check if the 2023.0 version install correctly like if /opt/intel/oneapi/mkl/2023.0.0/ exist.
2. If you install correctly, please try to logout your current ssh session and relogin. Then source oneapi again.

**Comment by dyedd** [comment]
> > > env | grep LD_LIBRARY_PATH
> > 
> > 
> > ```
> > LD_LIBRARY_PATH=/opt/intel/oneapi/vpl/2022.2.5/lib:/opt/intel/oneapi/tbb/2021.7.1/env/../lib/intel64/gcc4.8:/opt/intel/oneapi/mpi/2021.7.1//libfabric/lib:/opt/intel/oneapi/mpi/2021.7.1//lib/release:/opt/intel/oneapi/mpi/2021.7.1//lib:/opt/intel/oneapi/mkl/2022.2.1/lib/intel64:/opt/intel/oneapi/itac/2021.7.1/slib:/opt/intel/oneapi/ippcp/2021.6.2/lib/intel64:/opt/intel/oneapi/ipp/2021.6.2/lib/intel64:/opt/intel/oneapi/dnnl/2022.2.1/cpu_dpcpp_gpu_dpcpp/lib:/opt/intel/oneapi/debugger/2021.7.1/gdb/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/libipt/intel64/lib:/opt/intel/oneapi/debugger/2021.7.1/dep/lib:/opt/intel/oneapi/dal/2021.7.1/lib/intel64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/x64:/opt/intel/oneapi/compiler/2022.2.1/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi/compiler/2022.2.1/linux/compiler/lib/intel64_lin:/opt/intel/oneapi/ccl/2021.7.1/lib/cpu_gpu_dpcpp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It's very strange. Just now I have followed oneapi2023？？？
> 
> 1. Please help to check if the 2023.0 version install correctly like if /opt/intel/oneapi/mkl/2023.0.0/ exist.
> 2. If you install correctly, please try to logout your current ssh session and relogin. Then source oneapi again.

thanks！！！I find the error. environment variables are funny.
It was successfully installed with oneapi 2022 last year, but I didn't expect that the old version would be unavailable after the release of 2023.
