### ISSUE TITLE
Please update pybind11's version

### ISSUE THREAD

**Issue by heligan** [intel/intel-extension-for-tensorflow#27]
Hi,

I am compiling the extension with python 3.11 and got an error related to pybind11:

```
member access into incomplete type 'PyFrameObject'
```

The issue is that the current version of pybind11 (2.6.0) is too old for python 3.11.

https://github.com/intel/intel-extension-for-tensorflow/blob/main/itex/workspace.bzl#L61

According to the doc of pybind11

https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-10-1-oct-31-2022

the minimal version to support python 3.11 is 2.10.1. I made the following changes to the `workspace.bzl` file and it seems to build fine with python 3.11.

```
    tf_http_archive(
        name = "pybind11",
        urls = [
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/pybind/pybind11/archive/v2.10.1.tar.gz",
            "https://github.com/pybind/pybind11/archive/v2.10.1.tar.gz",
        ],
        sha256 = "111014b516b625083bef701df7880f78c2243835abdb263065b6b59b960b6bad",
        strip_prefix = "pybind11-2.10.1",
        build_file = clean_dep("//third_party:pybind11.BUILD"),
        system_build_file = clean_dep("//third_party/systemlibs:pybind11.BUILD"),
    )
```

feel free to try even later versions.

**Comment by guizili0** [comment]
@heligan thanks for reporting this issue, we just fix this in latest master with https://github.com/intel/intel-extension-for-tensorflow/commit/e728ca9e524171c723c1453e3cdd6104e3727091

**Comment by heligan** [comment]
Glad that it's fixed.
