### ISSUE TITLE
container: gpu-max: add missing env variables for horovod/mpi use

### ISSUE THREAD

**Issue by tkatila** [intel/intel-extension-for-tensorflow#29]
The gpu-max variant has all the libraries for horovod&mpi execution, but out-of-the-box those tools (and their libraries) are not found.
To manually enable usage:
```
export PATH=/opt/intel/oneapi/lib/intel64/bin:$PATH
export I_MPI_ROOT=/opt/intel/oneapi/lib/intel64/
export CCL_ROOT=/opt/intel/oneapi/lib/intel64/
export LD_LIBRARY_PATH=/opt/intel/oneapi/lib/intel64/libfabric:$LD_LIBRARY_PATH
```

**Comment by NeoZhangJianyu** [comment]
@tkatila 
Do you mean the container should be added to variants as you list?

```
export PATH=/opt/intel/oneapi/lib/intel64/bin:$PATH
export I_MPI_ROOT=/opt/intel/oneapi/lib/intel64/
export CCL_ROOT=/opt/intel/oneapi/lib/intel64/
export LD_LIBRARY_PATH=/opt/intel/oneapi/lib/intel64/libfabric:$LD_LIBRARY_PATH
```
Thank your feedback!

**Comment by tkatila** [comment]
> @tkatila Do you mean the container should be added to variants as you list?

Yes, I think the env variables should be added to the gpu-max container.

**Comment by NeoZhangJianyu** [comment]
@tkatila 
OK, it's clear!

We will update the gpu-max container.

Thank you very much!

**Comment by tkatila** [comment]
I see 1.2.0-gpu-horovod container includes fix for this. Thanks!

Feel free to close this.

**Comment by tkatila** [comment]
This seems to be a valid bug again. I checked `intel/intel-extension-for-tensorflow:2.14.0.1-xpu` and `intel/intel-extension-for-tensorflow:xpu` images, and both of them did not have the env variable anymore and I couldn't find any env scripts that would add the missing variables.

**Comment by wangkl2** [comment]
@tkatila Please add these env variables manually in the docker container based on this guide: https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_xpu.md#get-docker-container-from-dockerhub 
```
$ export LD_LIBRARY_PATH=/opt/intel/oneapi/redist/opt/mpi/libfabric/lib:$LD_LIBRARY_PATH
$ export PATH=/opt/intel/oneapi/redist/bin:$PATH
$ export I_MPI_ROOT=/opt/intel/oneapi/redist/lib
$ export CCL_ROOT=/opt/intel/oneapi/redist
$ export FI_PROVIDER_PATH=/opt/intel/oneapi/redist/opt/mpi/libfabric/lib/prov
```

**Comment by wangkl2** [comment]
@tkatila From v2.13.0.0, we combine `gpu` and `gpu-horovod` into 1 single `xpu` version of docker image. Since non-horovod users do not require these env variables for oneAPI runtime, while horovod users need, as a result, to avoid ruining the non-horovod users' contianer environment, we add these extra env variables in the installation guide only for those distributed workloads.

**Comment by tkatila** [comment]
@wangkl2 sure, I understand the reasoning there.

I'd like to promote an idea of a "horovod-vars.sh" script that a user could source. That way the correct set of variables would be contained within the container. If the paths ever change, the script could be adjusted and the user could keep using it without knowing about the details.
