### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by microyea** [intel/intel-extension-for-tensorflow#35]
[latest build from source](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/how_to_build.html)

**Comment by yinghu5** [comment]
@microyea Thank you a lot for the report.  Will fix it and keep you updated!

**Comment by ZhaoqiongZ** [comment]
Hi @microyea , thanks again for your report! We have fixed it now!
