### ISSUE TITLE
Confused on instructions for installing intel-extension-for-tensorflow[gpu]

### ISSUE THREAD

**Issue by tedliosu** [intel/intel-extension-for-tensorflow#4]
On your website for installing the GPU extension [here](https://www.intel.com/content/www/us/en/developer/articles/technical/innovation-of-ai-software-extension-tensorflow.html), it says that "Intel® Data Center GPU Flex Series Driver" is needed as a prerequisite for installing the GPU extension for tensorflow? I'm very confused as to why I'd be needing Data Center GPU drivers as the only Intel GPU I have on my machine (on which I want to install the GPU extension) is a consumer iGPU of the 11400H :confused:.

Please help me clarify on whether or not I actually need the "Data Center GPU Flex Series Driver" or if that is just listed on the website for those who are actually running an Intel Data Center GPU Flex Series?

**Comment by yiqianglee** [comment]
@tedliosu "Intel® Data Center GPU Flex Series Driver" is must if you want to run on "Intel® Data Center GPU Flex Serial", the reason we put it here is, "Intel® Data Center GPU Flex Series 170" is our official verified HW in this release. 
If you want to run on iGPU, make sure you have corrected driver installed, no need installs this version.

**Comment by tedliosu** [comment]
> @tedliosu "Intel® Data Center GPU Flex Series Driver" is must if you want to run on "Intel® Data Center GPU Flex Serial", the reason we put it here is, "Intel® Data Center GPU Flex Series 170" is our official verified HW in this release. If you want to run on iGPU, make sure you have corrected driver installed, no need installs this version.

@yiqianglee Thank you so much for the clarification! May I ask if it's alright to suggest changing the prerequisites installation instructions to something like this to minimize confusion for others in the future? As you can see I basically indented stuff that referred to the same thing as the item above and made the instructions slightly more specific :)

> 1. Pre-Installation Requirements
>     - Install Intel GPU driver
>         - IF running a Intel® Data Center GPU Flex Series, please find drivers [here](https://dgpu-docs.intel.com/releases/stable_419_40_20220914.html)
>         - Please find GPU driver installation guides for other Intel GPUs [here](https://dgpu-docs.intel.com/installation-guides/index.html)
>     - Install Intel® oneAPI Base Toolkit
>        - Install Intel® oneAPI Base Toolkit Packages 2022.3 from [here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html)

**Comment by yiqianglee** [comment]
> > @tedliosu "Intel® Data Center GPU Flex Series Driver" is must if you want to run on "Intel® Data Center GPU Flex Serial", the reason we put it here is, "Intel® Data Center GPU Flex Series 170" is our official verified HW in this release. If you want to run on iGPU, make sure you have corrected driver installed, no need installs this version.
> 
> @yiqianglee Thank you so much for the clarification! May I ask if it's alright to suggest changing the prerequisites installation instructions to something like this to minimize confusion for others in the future? As you can see I basically indented stuff that referred to the same thing as the item above and made the instructions slightly more specific :)
> 
> > 1. Pre-Installation Requirements
> >    
> >    * Install Intel GPU driver
> >      
> >      * IF running a Intel® Data Center GPU Flex Series, please find drivers [here](https://dgpu-docs.intel.com/releases/stable_419_40_20220914.html)
> >      * Please find GPU driver installation guides for other Intel GPUs [here](https://dgpu-docs.intel.com/installation-guides/index.html)
> >    * Install Intel® oneAPI Base Toolkit
> >      
> >      * Install Intel® oneAPI Base Toolkit Packages 2022.3 from [here](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html)

@tedliosu Thanks for suggestion, I think it should be fine to make it clear.  + @riverliuintel

**Comment by riverliuintel** [comment]
This fix is ready in https://www.intel.com/content/www/us/en/developer/articles/technical/innovation-of-ai-software-extension-tensorflow.html
