### ISSUE TITLE
Unable to use progressive memory growth

### ISSUE THREAD

**Issue by hydra324** [intel/intel-extension-for-tensorflow#47]
Howdy,

I'm currently using intel Data center Max 1100 GPU and I want tensorflow to restrict memory usage to progressive by setting the environment variable `TF_FORCE_GPU_ALLOW_GROWTH=true` as mentioned in their [docs](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). However, when I check memory usage with `sysmon`, it still allocates almost all of the gpu memory to my process. I realize that this configuration is paltform specific, hence why I would like to know if there is a way to restrict GPU memory usage on intel GPUs? Thank you!

Regards,
hydra324

**Comment by YuningQiu** [comment]
Hi, may I know the version of the TensorFlow and Intel Extension for TensorFlow that you are using?

**Comment by YuningQiu** [comment]
Also, did you try tf.config.experimental.set_memory_growth(device, enable) at [https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth]?

**Comment by guizili0** [comment]
@hydra324 please try to use "ITEX_LIMIT_MEMORY_SIZE_IN_MB"

**Comment by hydra324** [comment]
> @hydra324 please try to use "ITEX_LIMIT_MEMORY_SIZE_IN_MB"

Thank you! It works. Is there a similar env variable for letting the memory usage increase as needed instead of an upper bound?

**Comment by guizili0** [comment]
@hydra324 we did not limit the total memory usage, otherwise the workload wound report OOM when the memory usage is up to the limit, the workload still cannot run.
