### ISSUE TITLE
[Question] Why not to use OpenVINO for extending Tensorflow ?

### ISSUE THREAD

**Issue by redradist** [intel/intel-extension-for-tensorflow#48]
Previously OpenVINO had package for extending Tensorflow [openvino_tensorflow](https://github.com/openvinotoolkit/openvino_tensorflow)
But now it is abandoned in favour of this package ...

As for me OpenVINO is more suitable for extending Tensorflow and PyTorch (as it already doing as mentioned in the following issue https://github.com/openvinotoolkit/openvino/discussions/16472)
The reason is that it supports multiple-devices, different plugins, extensions, IR optimizations and etc.

OpenVINO is already doing `evaluation` aka `inference` and also it could be used for training like mentioned in https://github.com/openvinotoolkit/openvino_tensorflow for PyTorch

I understand that `intel-extension-for-tensorflow` is mostly concentrated on implementing this extension with `oneAPI`, but it could be done as separate plugin in OpenVINO infrastructure named for example `one_plugin`

As for me a lot of the same work done in both teams

Related issue:
[Use OpenVINO as backend for Tensorflow and PyTorch for training](https://github.com/openvinotoolkit/openvino/discussions/16472)
[[Question] Why not to use OpenVINO for extending Tensorflow ?](https://github.com/intel/intel-extension-for-tensorflow/issues/48)
[[Question] Why not to use OpenVINO for extending PyTorch as it is already doing ?](https://github.com/intel/intel-extension-for-pytorch/issues/440)

**Comment by YuningQiu** [comment]
Hi, many thanks for this question. However, we don't have the position to answer this question. Please go to the OpenVINO github issue https://github.com/openvinotoolkit/openvino_tensorflow/issues, and hope this can help.

**Comment by redradist** [comment]
> Hi, many thanks for this question. However, we don't have the position to answer this question. Please go to the OpenVINO github issue https://github.com/openvinotoolkit/openvino_tensorflow/issues, and hope this can help.

@YuningQiu Why ? You are both teams of Intel, for me it looks like internal discussion
Also I've already raised this question on [openvino_tensorflow/issues](https://github.com/openvinotoolkit/openvino_tensorflow/issues) see [[Question] Why openvino_tensorflow is abandoned ?](https://github.com/openvinotoolkit/openvino_tensorflow/issues/433)

**Comment by YuningQiu** [comment]
Yes, we will also work on the answer together with OpenVino team internally. And we are happy that you have already raised the question on [openvino_tensorflow/issues](https://github.com/openvinotoolkit/openvino_tensorflow/issues), so that OpenVino team can provide you with the answer in a more direct and efficient way. Thanks again!

**Comment by redradist** [comment]
> Some difference between OV and ITEX based on tech view: Compare with OV, ITEX is the official plugin of TensorFlow, please see the [link](https://blog.tensorflow.org/2022/10/accelerating-tensorflow-on-intel-data-center-gpu-flex-series.html) for more details. That means ITEX is more of a component in TF community than a modular from third-party, which can be compatible with original TF model without any model code changes and will be easy to extend with other community features (e.g. XLA, MLIR) in future.

@Zantares But, again, it is a lot of code duplication ...

ITEX is anyway "third-party" integration because it uses oneDNN

**Comment by cboss6** [comment]
@redradist 
Habana have supported full tech stacks including PT, TF, HVD and so on. According to your opinion, why OV?
What's more, as far as I known, OV is focus on inference mainly, may I ask why does ultimate inference application requires an inference engine to increase extra overhead?

**Comment by redradist** [comment]
@cboss6 
> @redradist Habana have supported full tech stacks including PT, TF, HVD and so on. According to your opinion, why OV?

Because it has a good generalized architecture, plenty the same algorithms, lots of operations needed for training, including ConvBackward and because it also written by Intel and it make sense to combine forces

> What's more, as far as I known, OV is focus on inference mainly, may I ask why does ultimate inference application requires an inference engine to increase extra overhead?

Not only the inference, see comment https://github.com/openvinotoolkit/openvino/discussions/16472#discussioncomment-7080385

**Comment by Zantares** [comment]
> @Zantares But, again, it is a lot of code duplication ...
> 
> ITEX is anyway "third-party" integration because it uses oneDNN

Not exactly, you may be aware of that oneDNN has become part of CPU path in stock TF from [2.5.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0) and was turned on by default from [2.9.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.9.0). At least the "third-party" is not indicated by `oneDNN`, it's more related to how the FWK designed. On other hand, ITEX will soon support XLA, it follows what the community is doing.

**Comment by yinghu5** [comment]
thank everyone's discussion here.  it seems no exact issue left here so go ahead to close it.
