### ISSUE TITLE
Do you support multi-card training, e.g. 2 A770s?

### ISSUE THREAD

**Issue by AustinKuture** [intel/intel-extension-for-tensorflow#49]
How should I configure the environment for training with multiple cards

**Comment by nazneenn** [comment]
Intel® Extension for TensorFlow* is compatible with stock Tensorflow*.  ITEX provides XPUAutoShard feature to automatically shard the input data and the TensorFlow graph to Intel® GPU devices to maximize hardware usage. Currently, it supports applying the shards on multiple GPU tiles to maximize the hardware utilization and improve performance.

For more information please go through - https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/guide/XPUAutoShard.md#xpuautoshard-on-gpu-experimental

In addition, to run distributed training on Intel GPU Intel® Optimization for Horovod* is available for tensorflow to run the distributed workload faster and easier.
Example link - https://github.com/intel/intel-extension-for-tensorflow/tree/main/examples/train_horovod

**Comment by yinghu5** [comment]
@AustinKuture ,  Hello, 
I'm glad to notify you that we publish the video to show  how to conduct train a CNN Model on Multiple Arc™ GPUs(https://www.youtube.com/watch?v=G5JpBpO6o74) 
for your reference!
