### ISSUE TITLE
Problems with ARC GPU on X15 laptop

### ISSUE THREAD

**Issue by sivyjyar** [intel/intel-extension-for-tensorflow#54]
Hi! 

I have a problem with my intel ARC 730M on intel X15 laptop
i have Ubuntu 22.04 on it
First of all, ARC gpu  is only used as display controller, not VGA

i mean command lspci | grep ' VGA ' | cut -d" " -f 1 | xargs -i lspci -v -s {} gives
00:02.0 VGA compatible controller: Intel Corporation Alder Lake-P Integrated Graphics Controller (rev 0c) (prog-if 00 [VGA controller])
	DeviceName: Onboard - Video
	Subsystem: Intel Corporation Device 3029
	Flags: bus master, fast devsel, latency 0, IRQ 183, IOMMU group 0
	Memory at 642c000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 4000000000 (64-bit, prefetchable) [size=256M]

but command lspci | grep ' Display ' | cut -d" " -f 1 | xargs -i lspci -v -s {}
03:00.0 Display controller: Intel Corporation Device 5691 (rev 08)
	Subsystem: Intel Corporation Device 3029
	Flags: bus master, fast devsel, latency 0, IRQ 184, IOMMU group 17
	Memory at 83000000 (64-bit, non-prefetchable) [size=16M]
	Memory at 6000000000 (64-bit, prefetchable) [size=16G]

and i'm a little bit worried, that my laptop is working only with integrated graphics. how can i check it?
i have already installed all drivers, as i think

and while using python -c "import intel_extension_for_tensorflow as itex; print(itex.__version__)"
error appears:

2023-11-22 14:20:58.925395: E itex/core/wrapper/itex_gpu_wrapper.cc:49] Could not load Intel Extension for Tensorflow* GPU backend, GPU will not be used.
If you need help, create an issue at https://github.com/intel/intel-extension-for-tensorflow/issues
2023-11-22 14:20:58.925592: E itex/core/wrapper/itex_gpu_wrapper.cc:49] Could not load Intel Extension for Tensorflow* GPU backend, GPU will not be used.

**Comment by guizili0** [comment]
@sivyjyar for Driver installation, please use https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_xpu.md
For driver verification, you can use [clinfo](https://manpages.ubuntu.com/manpages/focal/en/man1/clinfo.1.html)

**Comment by xiguiw** [comment]
@sivyjyar Could you import intel_extension_for_tensorflow successfully now?

**Comment by sivyjyar** [comment]
> @sivyjyar Could you import intel_extension_for_tensorflow successfully now?

yep, and i have written my own guide for this)

Laptop:  Intel NUC X15 LAPAC71H I7-12700H, Intel ARC 730M 
OS: Ubuntu 22.04.3 LTS

Installing drivers and extensions for tensorflow on the ARC730M graphics card

To install drivers on older versions of Ubuntu, you may need to install a kernel higher than 6.0. If the kernel (to check, use uname -r), like mine, 6.2 is not required.

The drivers are installed in the following sequence.
1) Configuring open source Mesa 3d graphics libraries for OpenGL and Vulkan
sudo add-apt-repository ppa:oibaf/graphics-drivers
sudo apt update
sudo apt upgrade
dpkg -l | grep -i mesa

we check if the opengl graphics card is detected
, install the library to check sudo apt install mesa-utils

to use a discrete graphics card, you need to set its priority DRI_PRIME=1
. check with glxinfo:
glxinfo -B | grep -i device   ---> Device: Mesa Intel(R) Graphics (ADL GT2) (0x46a6)

After that, set the environment variable PRIME:
export DRI_PRIME=1
glxinfo -B | grep -i device  --->Device: Mesa Intel(R) Arc(tm) A730M Graphics (DG2) (0x5691)

we check the operation of the video card in the glmark2 benchmark:
install sudo apt install glmark2

export DRI_PRIME=1
glxinfo -B | grep -i device
glmark2

glmark2 opens in a separate window, and our video card should be displayed in the terminal opposite GL_RENDER. 

2)install the latest Intel Compute drivers.
in the root folder, create a folder (mkdir neo)
and download all the necessary packages:

cd neo
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.14828.8/intel-igc-core_1.0.14828.8_amd64.deb
wget https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.14828.8/intel-igc-opencl_1.0.14828.8_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/intel-level-zero-gpu-dbgsym_1.3.26918.9_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/intel-level-zero-gpu_1.3.26918.9_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/intel-opencl-icd-dbgsym_23.30.26918.9_amd64.ddeb
wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/intel-opencl-icd_23.30.26918.9_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/libigdgmm12_22.3.0_amd64.deb

we check if everything was downloaded correctly

wget https://github.com/intel/compute-runtime/releases/download/23.30.26918.9/ww30.sum
sha256sum -c ww30.sum

installing all
sudo dpkg -i *.deb packages

3) install oneAPI libraries

wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo gpg --dearmor --output /usr/share/keyrings/oneapi-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
sudo apt-get update

sudo apt-get install intel-oneapi-runtime-dpcpp-cpp intel-oneapi-runtime-mkl

then you need to install oneAPI DPC+++ Compiler and oneAPI Math Kernel Library

wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/992857b9-624c-45de-9701-f6445d845359/l_BaseKit_p_2023.2.0.49397_offline.sh
sudo sh ./l_BaseKit_p_2023.2.0.49397_offline.sh

follow the instructions on the screen, do not change anything. 
setting the necessary environment variables:

source /opt/intel/oneapi/setvars.sh

4) proceed to installing the TensorFlow add-on

first, let's install pip and the tensor itself of a certain version

sudo apt install pip
pip install --upgrade pip
pip install 'tensorflow==2.13.0'


installing the Intel add-on:

pip install --upgrade intel-extension-for-tensorflow[gpu]

5) check if everything worked out for us

bash /path to site-packages/intel_extension_for_tensorflow/tools/env_check.sh

in my case, the command looked like this
cd ~/.local/lib/python3.10/site-packages/intel_extension_for_tensorflow/tools/
(it's better to run gedit env_check right away.sh and replace python with python3 in line 469)

bash env_check.sh

if it lights up red when checking libraries, we solve it using the same
sudo apt install <library name>
. I couldn't solve this only with the level-zero library, but everything works without it

6) we check the work with an example

https://intel.github.io/intel-extension-for-tensorflow/v2.13.0.0/examples/quick_example.html

**Comment by xiguiw** [comment]
@sivyjyar

That's great!
And thank you very much for sharing you guide for this!
As  there are huge number of laptop users, this is really helpful for other uses as a good reference.
