### ISSUE TITLE
[Question] - Is it possible to do matrix multiplication on GPU of complex tensors?

### ISSUE THREAD

**Issue by gnbaker** [intel/intel-extension-for-tensorflow#55]
I would like to be able to use operations like tf.linalg.matmul and tf.einsum on the GPU with complex tensors.

If I do TF_CPP_MAX_VLOG_LEVEL=1, and run the following code it shows that it runs on device:XPU:0

x = tf.ones((3,3))
y = tf.ones((3,3))
z = tf.linalg.matmul(x,y)

The MatMul node has the following attribute
attr {
    name: "T"
    type: "type"
    allowed_values {
      list {
        type: DT_BFLOAT16
        type: DT_HALF
        type: DT_FLOAT
        type: DT_DOUBLE
        type: DT_INT32
        type: DT_INT64
        type: DT_UINT8
        type: DT_UINT16
        type: DT_UINT32
        type: DT_UINT64
        type: DT_COMPLEX64
        type: DT_COMPLEX128
      }
    }
  }

However, if I run (even when using a with device block)
x = tf.ones((3,3), dtype="complex64")
y = tf.ones((3,3), dtype="complex64")
z = tf.linalg.matmul(x,y)

it will run on the CPU.
It seems like the MatMul node for XPU:0 can handle complex dtypes, but it won't run it.

**Comment by feng-intel** [comment]
Yes.  MatMul of XPU does not support complex dtypes yet.  TF will fallback to CPU side.

May I ask why you have complex tensors ? Which model you need to run on XPU?

**Comment by gnbaker** [comment]
> Yes. MatMul of XPU does not support complex dtypes yet. TF will fallback to CPU side.
> 
> May I ask why you have complex tensors ? Which model you need to run on XPU?

Thanks for the info. I was actually using a library that does quantum many-body calculations that can dispatch the calculations to TF, and was hoping I might be able to get GPU acceleration by using TF.

**Comment by feng-intel** [comment]
Sorry. Until now, We don't have plan to support complex dtype for MatMul of XPU.
