### ISSUE TITLE
Running on CPU only fails. 

### ISSUE THREAD

**Issue by Tortoise17** [intel/intel-extension-for-tensorflow#67]
I am trying to run this example on CPU only
`https://github.com/intel/intel-extension-for-tensorflow/blob/main/examples/stable_diffussion_inference/stable_diffusion_inference.ipynb`

 and it is failing throwing error. `
TypeError: StableDiffusion.__init__() got an unexpected keyword argument 'precision'`

**Comment by xiguiw** [comment]
@Tortoise17  
Thanks for trying this example!

What's your environment, the ITEX version and stable diffusion version?

This error indicates 'precision' is not the expected argument of stable fussion __init__.

**Comment by Tortoise17** [comment]
@xiguiw  thank you for reply, So far, I have not separately downloaded the stable-diffusion as it has several versions and I thought with the first time execution, it should pick the download. If you have any advise which one to install or use.?  and itex i have just cloned this git repo and installed as in ReadMe

**Comment by Tortoise17** [comment]
DO I have to delete tensorflow? I guess that is what I did as extra maybe. My mistake??

**Comment by xiguiw** [comment]
Now I would suggest you to follow the install page to install ITEX:

https://intel.github.io/intel-extension-for-tensorflow/latest/docs/install/installation_guide.html

Then follow the guide to setup env.
https://github.com/intel/intel-extension-for-tensorflow/tree/main/examples/stable_diffussion_inference

Also, I'll try to reproduce the issue and find what's the problem.

Thanks!

**Comment by xiguiw** [comment]
@Tortoise17 
https://github.com/intel/intel-extension-for-tensorflow/blob/main/examples/stable_diffussion_inference/stable_diffusion_inference.ipynb
The example and the environment setup are for GPU.

If you need a example on CPU, please let me know. Then we'll create a new one.
