### ISSUE TITLE
HELP - linking errors during compilation when compiling tensorflow extension from source

### ISSUE THREAD

**Issue by tedliosu** [intel/intel-extension-for-tensorflow#8]
I basically followed instructions from [here](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/how_to_build.md) and it took over _90 minutes_ to partially build on my i5 11400H before I ran into the error below, how may I go about solving this error so that I can do a custom install of ITEX for my Tiger Lake iGPU per what I have learned from this other [issue](https://github.com/intel/intel-extension-for-pytorch/issues/253)?
```
ERROR: /home/tedliosu/Documents/all_git/intel-extension-for-tensorflow/itex/BUILD:3:16: Linking itex/libitex_gpu.so failed: (Exit 1): crosstool_wrapper_driver failed: error executing command external/local_config_dpcpp/crosstool_dpcpp/bin/crosstool_wrapper_driver @bazel-out/k8-opt/bin/itex/libitex_gpu.so-2.params
/lib/x86_64-linux-gnu/crti.o: in function `_init':
(.init+0xb): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
bazel-out/k8-opt/bin/external/onednn_gpu/libonednn_gpu.pic.a(gen_convolution.pic.o): in function `dnnl::impl::gpu::jit::type_t::str[abi:cxx11]() const':
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev]+0x117): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@@GLIBCXX_3.4.21' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev]+0x138): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@@GLIBCXX_3.4.21' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit6type_t3strB5cxx11Ev]+0x162): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::basic_streambuf<char, std::char_traits<char> >@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
bazel-out/k8-opt/bin/external/onednn_gpu/libonednn_gpu.pic.a(gen_convolution.pic.o): in function `dnnl::impl::gpu::jit::layout_t::str[abi:cxx11]() const':
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev]+0xed): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `std::__detail::__to_chars_10_impl<unsigned long>(char*, unsigned int, unsigned long)::__digits' defined in .rodata._ZZNSt8__detail18__to_chars_10_implImEEvPcjT_E8__digits[_ZZNSt8__detail18__to_chars_10_implImEEvPcjT_E8__digits] section in bazel-out/k8-opt/bin/itex/core/graph/onednn_graph/libonednn_graph.pic.lo(onednn_graph.pic.o)
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev]+0x8d0): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@@GLIBCXX_3.4.21' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev]+0x8f1): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@@GLIBCXX_3.4.21' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
gen_convolution.cpp:(.text._ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev[_ZNK4dnnl4impl3gpu3jit8layout_t3strB5cxx11Ev]+0x91b): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::basic_streambuf<char, std::char_traits<char> >@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so
bazel-out/k8-opt/bin/external/onednn_gpu/libonednn_gpu.pic.a(gen_convolution.pic.o): in function `dnnl::impl::gpu::jit::gen_convolution_fwd_t::pd_t::init(dnnl_engine*)':
gen_convolution.cpp:(.text._ZN4dnnl4impl3gpu3jit21gen_convolution_fwd_t4pd_t4initEP11dnnl_engine+0x8e): relocation truncated to fit: R_X86_64_PC32 against symbol `vtable for std::_Sp_counted_ptr_inplace<dnnl::impl::gpu::jit::conv_config_t, std::allocator<dnnl::impl::gpu::jit::conv_config_t>, (__gnu_cxx::_Lock_policy)2>' defined in .data.rel.ro._ZTVSt23_Sp_counted_ptr_inplaceIN4dnnl4impl3gpu3jit13conv_config_tESaIS4_ELN9__gnu_cxx12_Lock_policyE2EE[_ZTVSt23_Sp_counted_ptr_inplaceIN4dnnl4impl3gpu3jit13conv_config_tESaIS4_ELN9__gnu_cxx12_Lock_policyE2EE] section in bazel-out/k8-opt/bin/external/onednn_gpu/libonednn_gpu.pic.a(gen_convolution.pic.o)
gen_convolution.cpp:(.text._ZN4dnnl4impl3gpu3jit21gen_convolution_fwd_t4pd_t4initEP11dnnl_engine+0xd8): relocation truncated to fit: R_X86_64_GOTPCREL against symbol `__pthread_key_create@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libpthread.so
gen_convolution.cpp:(.text._ZN4dnnl4impl3gpu3jit21gen_convolution_fwd_t4pd_t4initEP11dnnl_engine+0x10d): additional relocation overflows omitted from the output
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
icx: error: linker command failed with exit code 1 (use -v to see invocation)
stdout (/home/tedliosu/.cache/bazel/_bazel_tedliosu/63b2a19de8a71b2b34bf1b063cf42f79/execroot/intel_extension_for_tensorflow/bazel-out/_tmp/actions/stdout-3763) exceeds maximum size of --experimental_ui_max_stdouterr_bytes=1048576 bytes; skipping
Target //itex/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6057.667s, Critical Path: 4350.36s
INFO: 2231 processes: 361 internal, 1870 local.
FAILED: Build did NOT complete successfully
```

**Comment by yiqianglee** [comment]
@tedliosu may I know is there any problem to directly "pip install ITEX"?

For build time, it's not related to GPU, it's more related to host side, long time is expected because we implement thousands of kernels (same as stock TF), can you paste more information for your host machine? Like lscpu, memory? And have you successfully build stock TF in your machine also? @Dboyqiao

**Comment by tedliosu** [comment]
> @tedliosu may I know is there any problem to directly "pip install ITEX"?
> 
> For build time, it's not related to GPU, it's more related to host side, long time is expected because we implement thousands of kernels (same as stock TF), can you paste more information for your host machine? Like lscpu, memory? And have you successfully build stock TF in your machine also? @Dboyqiao

Since you guys built the prepackaged ITEX with AOT for the latest intel data center GPUs, ITEX takes a very long time (i.e. 5+ min) to start doing any sort of useful work going from starting a tensorflow training script to actually running the training; I've also ran into issues where training in FP16 mixed precision makes performance _worse_ than FP32 training and I really want to confirm that it is due to a lack of support from oneDNN rather than the lack of official support for my intel iGPU i'm attempting to do the training on.  And no I didn't imply that my GPU was causing any slowdowns building TF I thought it was simply because my i5 11400H wasn't powerful enough to build ITEX quickly, which doesn't necessarily seem to be 100% the case now as you've said that you guys have implemented thousands of kernels into ITEX.  And no I haven't tried building stock TF because it works well out of the box with my mobile RTX 3050 so I have no reason to spend extra time building it from scratch.

btw here's more info about my machine for the record; anything more specific I need to provide to help solve this issue?

```
(base) tedliosu@victus-ted:~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           141
Model name:                      11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         4100.060
CPU max MHz:                     2701.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5376.00
Virtualization:                  VT-x
L1d cache:                       288 KiB
L1i cache:                       192 KiB
L2 cache:                        7.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled v
                                 ia prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Vulnerable: eIBRS with unprivileged eBPF
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rd
                                 tscp lm constant_tsc art arch_perfmon pebs bts 
                                 rep_good nopl xtopology nonstop_tsc cpuid aperf
                                 mperf tsc_known_freq pni pclmulqdq dtes64 monit
                                 or ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr 
                                 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc
                                 _deadline_timer aes xsave avx f16c rdrand lahf_
                                 lm abm 3dnowprefetch cpuid_fault epb cat_l2 inv
                                 pcid_single cdp_l2 ssbd ibrs ibpb stibp ibrs_en
                                 hanced tpr_shadow vnmi flexpriority ept vpid ep
                                 t_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 er
                                 ms invpcid rdt_a avx512f avx512dq rdseed adx sm
                                 ap avx512ifma clflushopt clwb intel_pt avx512cd
                                  sha_ni avx512bw avx512vl xsaveopt xsavec xgetb
                                 v1 xsaves split_lock_detect dtherm ida arat pln
                                  pts hwp hwp_notify hwp_act_window hwp_epp hwp_
                                 pkg_req avx512vbmi umip pku ospke avx512_vbmi2 
                                 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg 
                                 avx512_vpopcntdq rdpid movdiri movdir64b fsrm a
                                 vx512_vp2intersect md_clear ibt flush_l1d arch_
                                 capabilities
(base) tedliosu@victus-ted:~$ sudo -H dmidecode -t 17
[sudo] password for tedliosu: 
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.3.0 present.
# SMBIOS implementations newer than version 3.2.0 are not
# fully supported by this version of dmidecode.

Handle 0x0018, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x0014
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 16384 MB
	Form Factor: SODIMM
	Set: None
	Locator: Bottom - Slot 1 (left)
	Bank Locator: BANK 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 3200 MT/s
	Manufacturer: Avant Technology
	Serial Number: 00001863
	Asset Tag: 9876543210
	Part Number: J642GU44J2320NL     
	Rank: 1
	Configured Memory Speed: 3200 MT/s
	Minimum Voltage: 1.2 V
	Maximum Voltage: 1.2 V
	Configured Voltage: 1.2 V
	Memory Technology: DRAM
	Memory Operating Mode Capability: Volatile memory
	Firmware Version: Not Specified
	Module Manufacturer ID: Bank 6, Hex 0xF7
	Module Product ID: Unknown
	Memory Subsystem Controller Manufacturer ID: Unknown
	Memory Subsystem Controller Product ID: Unknown
	Non-Volatile Size: None
	Volatile Size: 16 GB
	Cache Size: None
	Logical Size: None

Handle 0x0019, DMI type 17, 92 bytes
Memory Device
	Array Handle: 0x0014
	Error Information Handle: Not Provided
	Total Width: 64 bits
	Data Width: 64 bits
	Size: 16384 MB
	Form Factor: SODIMM
	Set: None
	Locator: Bottom - Slot 2 (right)
	Bank Locator: BANK 0
	Type: DDR4
	Type Detail: Synchronous
	Speed: 3200 MT/s
	Manufacturer: Avant Technology
	Serial Number: 00001863
	Asset Tag: 9876543210
	Part Number: J642GU44J2320NL     
	Rank: 1
	Configured Memory Speed: 3200 MT/s
	Minimum Voltage: 1.2 V
	Maximum Voltage: 1.2 V
	Configured Voltage: 1.2 V
	Memory Technology: DRAM
	Memory Operating Mode Capability: Volatile memory
	Firmware Version: Not Specified
	Module Manufacturer ID: Bank 6, Hex 0xF7
	Module Product ID: Unknown
	Memory Subsystem Controller Manufacturer ID: Unknown
	Memory Subsystem Controller Product ID: Unknown
	Non-Volatile Size: None
	Volatile Size: 16 GB
	Cache Size: None
	Logical Size: None

(base) tedliosu@victus-ted:~$ uname -r
6.0.0-6.1-liquorix-amd64
(base) tedliosu@victus-ted:~$ gcc --version
gcc (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) tedliosu@victus-ted:~$ strings /usr/lib/gcc/x86_64-linux-gnu/11/libstdc++.so | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by Dboyqiao** [comment]
@tedliosu I could not reproduce this issue on my local host (i7-11700T). Could you provide the detail about your instructions? And which components have you installed by oneAPI Base Toolkit? 
Besides, what is your OS? ubuntu2.04 with kernel 6.0.0-6.1-liquorix-amd64?

**Comment by tedliosu** [comment]
> @tedliosu I could not reproduce this issue on my local host (i7-11700T). Could you provide the detail about your instructions? And which components have you installed by oneAPI Base Toolkit? Besides, what is your OS? ubuntu2.04 with kernel 6.0.0-6.1-liquorix-amd64?

@Dboyqiao I followed the instructions almost exactly as it was written [here](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/how_to_build.md), and the only key differences between what was written and what I did were the following:
1. I entered `tgllp,xe` for `Please specify the Ahead of Time(AOT) compilation platforms...`
2. Before running `bazel build -c opt --config=gpu  //itex/tools/pip_package:build_pip_package` I ran `export CPATH=/opt/intel/oneapi/vpl/latest/include:/opt/intel/oneapi/tbb/latest/include:/opt/intel/oneapi/mpi/latest/include:/opt/intel/oneapi/mkl/latest/include:/opt/intel/oneapi/ipp/latest/include:/opt/intel/oneapi/ippcp/latest/include:/opt/intel/oneapi/ipp/latest/include:/opt/intel/oneapi/dpl/latest/linux/include:/opt/intel/oneapi/dpcpp-ct/latest/include:/opt/intel/oneapi/dnnl/latest/cpu_dpcpp_gpu_dpcpp/include:/opt/intel/oneapi/dev-utilities/latest/include:/opt/intel/oneapi/dal/latest/include:/opt/intel/oneapi/ccl/latest/include/cpu_gpu_dpcpp` because I ran into the following error when trying to build with the default oneapi bash env setup:
```
ERROR: /home/tedliosu/.cache/bazel/_bazel_tedliosu/63b2a19de8a71b2b34bf1b063cf42f79/external/local_config_dpcpp/crosstool_dpcpp/BUILD:24:19: in cc_toolchain_suite rule @local_config_dpcpp//crosstool_dpcpp:toolchain: The include path '/opt/intel/oneapi/tbb/2021.7.0/env/../include' is not normalized.
Analyzing: target //itex/tools/pip_package:build_pip_package (71 packages loaded, 570 targets configured)
    Fetching @double_conversion; fetching
    Fetching @nsync; fetching
ERROR: /home/tedliosu/.cache/bazel/_bazel_tedliosu/63b2a19de8a71b2b34bf1b063cf42f79/external/local_config_dpcpp/crosstool_dpcpp/BUILD:24:19: in cc_toolchain_suite rule @local_config_dpcpp//crosstool_dpcpp:toolchain: The include path ''/opt/intel/oneapi/vpl/2022.2.0/include','/opt/intel/oneapi/tbb/2021.7.0/env/../include','/opt/intel/oneapi/mpi/2021.7.0//include','/opt/intel/oneapi/mkl/2022.2.0/include','/opt/intel/oneapi/ipp/2021.6.1/include','/opt/intel/oneapi/ippcp/2021.6.1/include','/opt/intel/oneapi/ipp/2021.6.1/include','/opt/intel/oneapi/dpl/2021.7.1/linux/include','/opt/intel/oneapi/dpcpp-ct/2022.2.0/include','/opt/intel/oneapi/dnnl/2022.2.0/cpu_dpcpp_gpu_dpcpp/include','/opt/intel/oneapi/dev-utilities/2021.7.0/include','/opt/intel/oneapi/dal/2021.7.0/include','/opt/intel/oneapi/ccl/2021.7.0/include/cpu_gpu_dpcpp'' is not normalized.
```

As for which components I have installed by oneAPI base toolkit, I have _all_ of them installed plus the hpckit as I simply did `sudo -H aptitude install intel-basekit intel-hpckit` when I first installed the oneAPI toolkits.  And yes my OS that I had been running at the time was Ubuntu 20.04 with kernel 6.0.0-6.1-liquorix-amd64 (I am running 5.15.0-52-generic
now after running into Nvidia driver issues with the newer kernel, but as I'll explain I don't think that made a difference in how I got the compilation to actually work on my end)

So actually in the meantime I did end up getting compilation to work by doing the following (I am simply stating what I did and since I didn't try each of those things individually I don't know which of those things actually made a difference in getting compilation to actually work; and YES I got compilation to work while I was still running kernel 6.0.0-6.1-liquorix-amd64):
1. I switched from compiling using gcc/g++ 11.1.0 to gcc/g++ 9.4.0
2. Dropped xe from the AOT options, but that's mostly to save time compiling for my own sanity.

Furthermore, after finishing compiling and test-running the built-from-source ITEX wheels, I realized that some scripts were impossible to run even with FP64 emulation because the wheels were built with the `-cl-poison-unsupported-fp64-kernels` option; therefore, I made the following patch to one of the `.bzl` build files to get things working again:
```
diff --git a/third_party/build_option/dpcpp_configure.bzl b/third_party/build_option/dpcpp_configure.bzl
index bb3abd9..5fb793e 100644
--- a/third_party/build_option/dpcpp_configure.bzl
+++ b/third_party/build_option/dpcpp_configure.bzl
@@ -123,7 +123,7 @@ def find_mkl_path(repository_ctx):

 def find_aot_config(repository_ctx):
     """Find AOT config."""
-    aot_config = " -Xs \'-options -cl-poison-unsupported-fp64-kernels\'"
+    aot_config = " -Xs "
     device_tmp = " -fsycl-targets=spir64_gen,spir64 -Xs \'-device {}\'"
     if _AOT_CONFIG in repository_ctx.os.environ:
         devices = repository_ctx.os.environ[_AOT_CONFIG].strip()
````

As for the initial issues of long tensorflow initialization times and seeing whether or not the worse FP16 mixed precision training was due to lack of FP16 training support from both oneDNN and ITEX I was trying to solve by installing ITEX from source with AOT support added for my Intel iGPU, I learned the following from test-running the ITEX I'd built from source:
1. Yes, initialization times improved by many fold with the default build arguments/config, but unfortunately as `-cl-poison-unsupported-fp64-kernels` was one of them I had to remove it as some of my scripts wouldn't run otherwise, and by removing it initialization times shot back up to being several minutes in length again, which is quite a shame as it speaks to how much more performant tensorflow initialization could've been if and only if Intel in their "infinite wisdom" _didn't_ remove those FP64 cores from gen 11+ graphics architectures.
2. By building ITEX from source with AOT support for my intel iGPU, mixed precision FP16 training with `tensorflow.keras.mixed_precision` DID improve but only ended up exactly matching how fast FP32 training was without any mixed precision; furthermore, using ITEX's built-in automatic mixed precision feature to do mixed precision FP16 training _still_ saw performance degradation compared to normal FP32 training, so I think it's safe to say that the performance degradation I'm observing here with mixed precision FP16 training is due to lack of such support from both oneDNN and ITEX, and so I'll open separate issues for both ITEX and oneDNN to request FP16 training support as I seriously can't see why it isn't supported given esp. how not only the latest Arc GPUs support BOTH BF16 _and_ FP16 XMX operations, but that it'll also permit a greater variety of Intel graphics to be able to enjoy faster training times.

Feel free to close this issue if you don't have any more questions about the issues I ran into and how I managed to solve the compilation issues :smile:

**Comment by yiqianglee** [comment]
@tedliosu Really appreciate your keeping trying, good to know you can run it now. 👍 
For #1, FP64 kernel support, yes, we are not allowing "FP64 emulation", the reason is, "FP64 emulation" is only experimental feature, quality is not guaranteed, `-cl-poison-unsupported-fp64-kernels` will only remove those FP64 kernel in the machine without FP64 native support, that will not impact to run on other machine, and furthermore, this will only impact those models who really want to use "FP64" ops, if your models don't really run FP64 ops, it should not have difference. 
For #2, FP16 training is not there as you mentioned, we can discuss in separate issues.

**Comment by yiqianglee** [comment]
Close issue as reporter already solve the problem.
